### ISSUE TITLE
Punctuation at the start of cmudict

### ISSUE THREAD

**Issue by hugovk** [aparrish/pronouncingpy#12]
``` python
>>> import pronouncing
>>> pronouncing.rhymes("period")
[u'.period', u'myriad']
>>> pronouncing.rhymes("hyphen")
[u'-hyphen', u'siphon', u'syphon']
```

That `.period` is a bit strange. This is because [cmudict-0.7b](https://github.com/aparrish/pronouncingpy/blob/master/pronouncing/cmudict-0.7b) begins with a load of symbols:

```
!EXCLAMATION-POINT  EH2 K S K L AH0 M EY1 SH AH0 N P OY2 N T
"CLOSE-QUOTE  K L OW1 Z K W OW1 T
"DOUBLE-QUOTE  D AH1 B AH0 L K W OW1 T
"END-OF-QUOTE  EH1 N D AH0 V K W OW1 T
"END-QUOTE  EH1 N D K W OW1 T
"IN-QUOTES  IH1 N K W OW1 T S
...
```

So this isn't necessarily a bug in Pronouncing, but more a case of how to interpret the input data. (In a way it's `.` that rhymes with `period` and not `.period`; `-` rhymes with `hyphen` and not `-hyphen`.) Would it make sense to filter some of these out? 

This isn't a problem for me, I just noticed it in some unusual output and thought I'd mention it.

If they were filtered, care should be taken not to filter things like:

```
'ALLO  AA2 L OW1
'BOUT  B AW1 T
'CAUSE  K AH0 Z
'COURSE  K AO1 R S
'CUSE  K Y UW1 Z
```

**Comment by aparrish** [comment]
fixed as noted in david's PR.
