### ISSUE TITLE
Docs for rhyming_part assume phones_for_word returns string, not a list 

### ISSUE THREAD

**Issue by hugovk** [aparrish/pronouncingpy#24]
https://pronouncing.readthedocs.io/en/latest/pronouncing.html#pronouncing.rhyming_part says:

```python
>>> import pronouncing
>>> phones = pronouncing.phones_for_word("purple")
>>> pronouncing.rhyming_part(phones)
u'ER1 P AH0 L'
```
> Parameters:	phones – a string containing space-separated CMUdict phones
Returns:	a string with just the “rhyming part” of those phones

---

However, `phones_for_word` returns a list, not a string (Python 2.7.12, pronouncing==0.1.3):
```python
>>> import pronouncing
>>> phones = pronouncing.phones_for_word("purple")
>>> phones
[u'P ER1 P AH0 L']

>>> pronouncing.rhyming_part(phones)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pronouncing/__init__.py", line 143, in rhyming_part
    phones_list = phones.split()
AttributeError: 'list' object has no attribute 'split'

>>> pronouncing.rhyming_part(phones[0])
u'ER1 P AH0 L'
```

---

The `rhyming_part` examples in 
https://pronouncing.readthedocs.io/en/latest/tutorial.html?highlight=rhyming_part#rhyme work as expected.

**Comment by hugovk** [comment]
Perhaps doctest should be run on the CI?

**Comment by aparrish** [comment]
doctest should probably be in CI, yeah. that was always the intention, just never got around to it.
