### ISSUE TITLE
Cookbook: Example output incorrect?

### ISSUE THREAD

**Issue by wiseman** [aparrish/pronouncingpy#3]
In the first [Meter](https://pronouncing.readthedocs.org/en/latest/tutorial.html#meter) example:
```
>>> import pronouncing
>>> phones_list = pronouncing.phones_for_word("snappiest")
>>> pronouncing.stresses(phones_list[0])
u'0102'
```

But when I try that code I get this:

```
>>> import pronouncing
>>> phones_list = pronouncing.phones_for_word("snappiest")
>>> pronouncing.stresses(phones_list[0])
u'102'
```

**Comment by hugovk** [comment]
cmudict has `SNAPPIEST  S N AE1 P IH0 EH2 S T` so `u'102'` makes sense. 

PR to fix this: https://github.com/aparrish/pronouncingpy/pull/5

**Comment by aparrish** [comment]
yep, this was a typo (I probably had a different code example initially and forgot to copy over the resulting output when I changed the example).
