### ISSUE TITLE
pronouncing.phones_for_word("a") returns ['AH0', 'EY1', 'EY1 F AO1 R T UW1 W AH1 N T UW1 EY1 T']

### ISSUE THREAD

**Issue by denisfitz57** [aparrish/pronouncingpy#34]
The third result seems incorrect.

**Comment by hugovk** [comment]
It does!

Looks like some oddness in the CMU dictionary, which begins:

> A  AH0
A(1)  EY1
A'S  EY1 Z
A.  EY1
A.'S  EY1 Z
A.S  EY1 Z
A42128  EY1 F AO1 R T UW1 W AH1 N T UW1 EY1 T
AA  EY2 EY1

**Comment by hugovk** [comment]
The problem is here:

https://github.com/aparrish/pronouncingpy/blob/master/pronouncing/__init__.py#L30

Stripping the brackets and numbers means the word A42128 is interpreted as the word A.

**Comment by hugovk** [comment]
See PR https://github.com/aparrish/pronouncingpy/pull/36 for a fix with tests.

**Comment by aparrish** [comment]
weird, I wonder why "A42128" is even in there in the first place.

**Comment by hugovk** [comment]
I've no idea, but it is [quite a nice shade of red](http://www.color-hex.com/color/A42128).

**Comment by denisfitz57** [comment]
This may be relevant:
https://www.youtube.com/watch?v=2t6JJL2mEdM

How to Pronounce A42128 / How to Say A42128

**Comment by hugovk** [comment]
Ha, that video is just generated from the same CMU Pronouncing Dictionary!

Maybe it's a Mountweazel. https://en.m.wikipedia.org/wiki/Fictitious_entry
