### ISSUE TITLE
Switch CMUDICT Source to GitHub

### ISSUE THREAD

**Issue by davidlday** [aparrish/pronouncingpy#37]
Would you be open to switching to use the cmudict files from their [github](https://github.com/cmusphinx/cmudict) repo? The data's split out more cleanly, and it opens the possibility of automatically packaging / deploying this library when the cmudict repo is updated. It *may* also help with a couple of open issues - not sure yet.

I actually started writing a python wrapper for cmudict this morning but stopped when I came across your library. I'd rather contribute here than create something new since this package meets my needs as well. I'd be happy to work on making the changes necessary.

**Comment by aparrish** [comment]
sure, I'd be open to that! can you explain in a bit more detail what you're proposing?

**Comment by davidlday** [comment]
Here's what I had in mind:

1. restructure the package a little by adding a cmudict directory under pronouncing that keeps a copy of the cmudict files from their repo:

```
pronouncing/
    |-cmudict/
        |-cmudict.dict
        |-cmudict.phones
        |-cmudict.symbols
        |-cmudict.vp
        |-LICENSE
        |-etc...
```

2. add a tracking file to pronouncing that contains the SHA-1 hash of the last commit of cmudict when last built (call it ```pronouncing/CMUDICT_VERSION```)

3. add a custom build class to setup.py that handles updating the cmudict files:

    1. clone the cmudict repo in a temp directory

    2. ```git rev-parse HEAD``` on the repo

    3. compare that hash to the one stored in ```pronouncing/CMUDICT_VERSION```

    4. if they don't match, create a new branch on this repo, copy the new files in, update ```pronouncing/CMUDICT_VERSION``` with the latest commit hash, and submit a pull request

4. the version number for pronouncing would get updated manually during the pull request

I'm still working out the piece around automating branching and pull request, but I was planning on doing it manually in my package since cmudict doesn't have a lot of updates. I get notified when they commit changes. I'd be willing to do the same here as well.

I'm drafting out how this will work over in my own repo, but it'll easily port over here if you're interested.

Another possibility is that I make a lightweight package that only contains the cmudict files and provides their location (similar to how [certifi](https://github.com/certifi/python-certifi) works for Mozilla's root certificates bundle) and you could just use it in this package.

> "...I wanted to be able to use the CMU Pronouncing Dictionary in my projects (and teach other people how to use it) without having to install the grand behemoth that is NLTK."

This is my motivation, too!

**Comment by aparrish** [comment]
I'm more inclined to go with the certifi-esque route, and then just add that package as a dependency for this one, if that makes sense? The purpose of this library was always only to provide a reasonable interface—the data was just included as a convenience. I'm not overly eager to add a bunch of sophisticated machinery to the build process. Another advantage of separating the code and the data is that either could be upgraded separately without breaking backwards compatibility (e.g., if you wanted new pronunciation data in your application but *didn't* want to upgrade the library because of recent breaking changes). What do you think?

**Comment by davidlday** [comment]
Yep, the more I think about it, you're right about going the certifi route. It still avoids code duplication but separates updates of pronouncing from updates to the underlying cmudict files. I'll continue on my package as planned, focused on just bundling up the files, and I'll let you know when it's pushed to pypi. Thanks!

**Comment by davidlday** [comment]
Hi @aparrish - I now have a package available on pypi that packages up all the cmudict stuff (including the license file) if you're still interested. See the [GitHub repo](https://github.com/prosegrinder/python-cmudict) or [PyPi](https://pypi.org/project/cmudict/) page for details. Would be happy to help with any conversion, but no worries if you're not inclined to switch. I have another project I needed to do this for anyhow.

**Comment by aparrish** [comment]
hi! this is great. if you have ideas or the beginnings of a PR to integrate I would be happy to work with you on it!

**Comment by davidlday** [comment]
I'll start a PR after doing a little prelim work to validate!
