### ISSUE TITLE
Get Phones in German Language

### ISSUE THREAD

**Issue by jhoelzl** [aparrish/pronouncingpy#38]
Hello,

thanks for this module. I want to get phonemes for word, e.g.:

```
import pronouncing
pronouncing.phones_for_word("hello")
```

However, i suppose these are only valid for English words, but i want to use it for German words (e.g. "hallo") as well. What is the best way to extend this library to this functionality?

Regards,
Josef

**Comment by hugovk** [comment]
This uses the [CMU Pronouncing Dictionary](http://www.speech.cs.cmu.edu/cgi-bin/cmudict) which unfortunately is only in English. 

Do you know of a German equivalent?

**Comment by jhoelzl** [comment]
Maybe we could use this one instead?
https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/

File: German / cmusphinx-voxforge-de.dic

**Comment by hugovk** [comment]
Yes, that looks possible. The formats are a bit different.

The English is like `<uppercase word><(another)><2 spaces><phones>`

```
ACTUALITY  AE2 K CH UW0 AE1 L AH0 T IY2
ACTUALIZE  AE1 K CH UW2 AH0 L AY2 Z
ACTUALLY  AE1 K CH UW2 AH0 L IY0
ACTUALLY(1)  AE1 K CH L IY0
ACTUALLY(2)  AE1 K SH AH0 L IY0
```

The German is like: `<lowercase word><1 space><phones>`

```
draperie D RR AAH P RR IIH
draperien D RR AH P EE RR IIH AX N
drastisch D RR AH S T IH SH
drastische D RR AH S T IH SH AX
drauf D RR AW F
```

The case difference doesn't matter, nor the optional `(n)`. The 1 space v. 2 space separator may be a little more tricky.

Anyway, would you like to test out this quick hack? (Note this isn't compatible with the original English file, it's just for testing.)

1. Replace pronouncing/cmudict-0.7b with cmusphinx-voxforge-de.dic
2. Add `line = line.replace(" ", "  ", 1)  # replace first occurence`
before `word, phones = line.split("  ")`
in pronouncing/\_\_init__.py: https://github.com/aparrish/pronouncingpy/compare/master...hugovk:german-phones

```python
>>> import pronouncing
>>> print(pronouncing.phones_for_word('dreierriegel'))
['D RR AY EX RR IIH G AX L']
```

**Comment by aparrish** [comment]
The functions that the package provides beyond parsing the data (e.g., finding rhymes, stresses, etc.) are all fairly specific to English and the CMU Pronouncing Dictionary, so I'm not sure what the utility of the package would be for other languages (or other data sources). An internationalized, cross-linguistic version of the library would certainly need to have a much more sophisticated structure (allowing for language-specific implementations of various functions and data sources in different formats with different capabilities). For the sake of clarity and simplicity, I'm inclined to keep this library English- and cmudict-specific for the time being, though I would be interested in collaborating on to make something like the cross-linguistic version outlined above.

And of course you're welcome to re-use any of the code in this library for parsing and working with the other data files that CMU Sphinx provides (like the German one you found).

**Comment by jhoelzl** [comment]
@hugovk thanks for your support, it works in this way.
@aparrish thanks for clarification

**Comment by jhoelzl** [comment]
For sake of completeness: I just found https://github.com/jmorrow0/deuPD which provides an easy way to produce a German pronunciation dictionary.

**Comment by Hamahmi** [comment]
@jhoelzl it seams that the repo isn't there any more https://github.com/jmorrow0/deuPD, where can I find it ?

**Comment by hugovk** [comment]
@jmorrow0 Hello, is your https://github.com/jmorrow0/deuPD still available somewhere? Thank you!
