### ISSUE TITLE
Can I do conda install?

### ISSUE THREAD

**Issue by amitjslearn** [aparrish/pronouncingpy#50]
Hi, I am using anaconda, so how do I do conda install, I went to [anaconda cloud](https://anaconda.org/auto/pypi_pronounce) there the name was **pypi_pronounce**  is it the same pronounce as this?, and also I saw that
> "Last upload: 5 years and 7 months ago ", 

I want the latest version.  How do I do it? Help much appreciated.

**Comment by hugovk** [comment]
Must be something else, that's older than this repo https://github.com/aparrish/pronouncingpy/commit/68545759cfdb86ed2dd8874af6fa43990e770b42

**Comment by amitjslearn** [comment]
> Must be something else, that's older than this repo [6854575](https://github.com/aparrish/pronouncingpy/commit/68545759cfdb86ed2dd8874af6fa43990e770b42)

Yeah, but I installed this using `python setup.py install `

**Comment by aparrish** [comment]
There is no "official" Anaconda package for Pronouncing, and I'm not responsible for the `pypi_pronounce` package that you found in their index. (I suspect it's from a completely unrelated project.) You should be able to install Pronouncing with `pip`, even when using Anaconda; [see the Anaconda instructions here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages)—no need to use `python setup.py install`.
