### ISSUE TITLE
suggested new methods

### ISSUE THREAD

**Issue by Mathemilda** [aparrish/pronouncingpy#57]
Hello developers, 
I'm so grateful for your work! I felt huge relief when I found your module. 
I'm not a linguist, I'm data analyst. I have been working on converting a text into phones for future analysis. In particular, I discovered that in your package the method `pronouncing.phones_for_word()` sometimes does not work with "s" and "'s" at a word end. For example, I can get phones for "pic" and "Streep", but not for "pics" and "Streep's". In addition I needed phones for sentences. So I created a couple of methods. First one add "s" or "z" to a existing phoneme list, depending on ending sound.  Second one takes a sentence with only letter symbols and coverts it into a phoneme list, if possible. If there are symbol sequence for which a phoneme list does not exists, then such sequence is returned at the end, too.  I needed it because I wanted to check how well my cleaning procedure worked.  I understand that there may be foreign words with "s" at the end which must be pronounced differently, but I wanted a native English speaker pronunciation.   
```
def adding_s(phone_list):
     fkptth = [ 'F', 'K', 'P', 'T', 'TH']
     chsh = ['CH',  'SH']
     if phone_list[-1] in fkptth:
          return phone_list+' S'
     elif phone_list[-1] in chsh: 
          return phone_list[-1] +  ' IH Z'
     else:
          return phone_list +" Z"

def phones_for_sentence(se):
    words = se.split()
    sounds = [pronouncing.phones_for_word(w) for w in se.split()]
    no_sound = ""
    for i in range(len(words)):
        if len(sounds[i]) == 0: 
            word_ = words[i]
            if word_[-2:]=="'s":
                word_ = word_[:-2]
                sou = pronouncing.phones_for_word(word_) 
                if len(sou)!=0:
                    sou = adding_s(sou[0])
                    sounds[i] = sou
            elif word_[-1]=="s":
                word_ = word_[:-1]
                sou = pronouncing.phones_for_word(word_)
                if len(sou)!=0:
                    sou = adding_s(sou[0])
                    sounds[i] = sou

            else:
                no_sound += words[i] + ' '
        else:
            sounds[i] = sounds[i][0] + ' '

    return sounds, no_sound

ms = "Meryl Streep's strong speech against Donald Trump at Golden Globes gets thumbs up from Hollywood Bollywood"
phones_for_sentence(ms)
jd = ''Johnny Depp Settles $25 Million Suit with Former Business Managers: Report'
phones_for_sentence(jd)
tv= "'The Voice' Kelly Clarkson and Jennifer Hudson Returning As Coaches For Season 15"
phones_for_sentence(tv)
```
As you see sentences require some previous cleaning from punctuation, emojies and such, but these procedures are well known for people who work with NLP, and if they are not implemented correctly, the function gives a warning in the form of list. 
What do you think of this? I can rework the first function to detect "s" or "'s" at the end, if you think that it will be more suitable for your module. Or something else which I missed due to my lack of linguistic knowledge.  I'm open to suggestions. 
I believe that other people may benefit from the functions, too.  Yes, I know that there could be a few ways to pronounce a word depending on a context. I can make a warning about it as well and leave a possibility for a user to change it to more suitable way. My point here is a function can streamline this process.  
Best regards,
Mya

**Comment by aparrish** [comment]
Hi! Thank you for this thoughtful suggestion. I think my preference is for the library to remain a fairly unmediated wrapper over the CMU Pronouncing Dictionary dataset—I don't want to be in the business of making judgments about heuristic techniques for determining pronunciations for out-of-vocabulary words. (I have a separate library, [Pincelate](https://github.com/aparrish/pincelate/), to help with that problem, and there are other grapheme-to-phoneme models trained on CMUdict that could help with that!) Likewise, the method you use for tokenizing a sentence into words is usually pretty application-specific, and I'm not inclined to "bake" some one or other tokenization technique into the library itself.

**Comment by Mathemilda** [comment]
Hello Allison, 
Thanks for you prompt reply. Sorry to annoy you with something you have already done. I wish you would have a link here to your Pincelate site. For some reason it did not show when I have been googling pronunciation in Python, but this one did. 
Best,
Mya
